import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import { getAuth, createUserWithEmailAndPassword } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { collection, doc, getDoc, getDocs, setDoc, addDoc, updateDoc, deleteDoc, serverTimestamp, writeBatch, query, orderBy } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { db, firebaseConfig } from './firebase-config.js';
import { $, escapeHtml, modal, closeModal, toast, usernameToEmail, normalizeUsername, formatDateTime, toLocalInputValue, localInputToIso, downloadText, csvEscape } from './utils.js';

let currentContainer=null;
export function adminNav(){return[
  {id:'admin-dashboard',label:'Dashboard',icon:'⌂'},
  {id:'admin-subjects',label:'Mata Pelajaran',icon:'▦'},
  {id:'admin-questions',label:'Bank Soal',icon:'✎'},
  {id:'admin-students',label:'Akun Siswa',icon:'👥'},
  {id:'admin-scores',label:'Nilai',icon:'★'},
  {id:'admin-settings',label:'Pengaturan',icon:'⚙'}
];}

export async function renderAdminPage(page,container){currentContainer=container; const map={
  'admin-dashboard':renderDashboard,'admin-subjects':renderSubjects,'admin-questions':renderQuestions,'admin-students':renderStudents,'admin-scores':renderScores,'admin-settings':renderSettings
}; return (map[page]||renderDashboard)(container);}

async function getAll(path){const snap=await getDocs(collection(db,path));return snap.docs.map(d=>({id:d.id,...d.data()}));}
async function renderDashboard(c){
  c.innerHTML='<div class="grid grid-4" id="stats"></div><div class="section-head"><div><h3>Aktivitas Ujian</h3><p>Nilai terbaru yang masuk.</p></div></div><div id="recentScores"></div>';
  const [subjects,users,attempts]=await Promise.all([getAll('subjects'),getAll('users'),getAll('attempts')]);
  const students=users.filter(x=>x.role==='student'); const submitted=attempts.filter(x=>x.status==='submitted'); const avg=submitted.length?Math.round(submitted.reduce((a,b)=>a+Number(b.score||0),0)/submitted.length):0;
  $('#stats').innerHTML=[['Mata Pelajaran',subjects.length,'📚'],['Siswa',students.length,'👥'],['Ujian Selesai',submitted.length,'✅'],['Rata-rata Nilai',avg,'★']].map(x=>`<div class="card stat-card"><div><small>${x[0]}</small><h3>${x[1]}</h3></div><div class="stat-icon">${x[2]}</div></div>`).join('');
  const recent=submitted.sort((a,b)=>dateMs(b.submittedAt)-dateMs(a.submittedAt)).slice(0,8);
  $('#recentScores').innerHTML=recent.length?scoreTable(recent):empty('Belum ada nilai','Nilai siswa akan muncul setelah ujian dikumpulkan.');
}

async function renderSubjects(c){
  c.innerHTML=`<div class="section-head"><div><h3>Kelola Mata Pelajaran</h3><p>Atur token, durasi, jadwal dan pengawasan ujian.</p></div><button id="addSubjectBtn" class="btn btn-primary">+ Tambah Mapel</button></div><div id="subjectAdminGrid" class="subject-grid"></div>`;
  $('#addSubjectBtn').onclick=()=>subjectForm(); const items=await getAll('subjects'); const root=$('#subjectAdminGrid');
  root.innerHTML=items.length?items.sort((a,b)=>(a.name||'').localeCompare(b.name||'')).map(s=>`<article class="card subject-card"><span class="subject-code">${escapeHtml(s.code||'MAPEL')}</span><h3>${escapeHtml(s.name)}</h3><p>${s.scheduleStart?`Mulai: ${formatDateTime(s.scheduleStart)}`:'Tanpa jadwal mulai'}<br>${s.scheduleEnd?`Selesai: ${formatDateTime(s.scheduleEnd)}`:'Tanpa jadwal selesai'}</p><div class="subject-meta"><span class="badge badge-indigo">${s.durationMinutes||60} menit</span><span class="badge ${s.active?'badge-green':'badge-slate'}">${s.active?'Aktif':'Nonaktif'}</span><span class="badge badge-amber">Token: ${escapeHtml(s.token||'-')}</span></div><div class="action-row"><button class="btn btn-outline" data-edit-subject="${s.id}">Edit</button><button class="btn btn-danger" data-delete-subject="${s.id}">Hapus</button></div></article>`).join(''):empty('Belum ada mata pelajaran','Tambahkan mata pelajaran pertama.');
  root.querySelectorAll('[data-edit-subject]').forEach(b=>b.onclick=()=>subjectForm(items.find(x=>x.id===b.dataset.editSubject)));
  root.querySelectorAll('[data-delete-subject]').forEach(b=>b.onclick=()=>deleteSubject(b.dataset.deleteSubject));
}
function subjectForm(s={}){
  modal({title:s.id?'Edit Mata Pelajaran':'Tambah Mata Pelajaran',subtitle:'Token dapat diganti kapan saja sebelum ujian.',body:`<div class="form-grid">
    <label class="field"><span>Nama Mata Pelajaran</span><input id="sName" value="${escapeHtml(s.name||'')}" placeholder="Matematika"></label>
    <label class="field"><span>Kode</span><input id="sCode" value="${escapeHtml(s.code||'')}" placeholder="MTK"></label>
    <label class="field"><span>Durasi (menit)</span><input id="sDuration" type="number" min="1" value="${Number(s.durationMinutes||60)}"></label>
    <label class="field"><span>Token Ujian</span><input id="sToken" value="${escapeHtml(s.token||'')}" placeholder="MTK2026"></label>
    <label class="field"><span>Jadwal Mulai</span><input id="sStart" type="datetime-local" value="${toLocalInputValue(s.scheduleStart)}"></label>
    <label class="field"><span>Jadwal Selesai</span><input id="sEnd" type="datetime-local" value="${toLocalInputValue(s.scheduleEnd)}"></label>
    <label class="field"><span>Maks. Peringatan Keluar Tab</span><input id="sWarnings" type="number" min="1" value="${Number(s.maxWarnings||3)}"></label>
    <div class="field"><span>Opsi</span><label class="check-row"><input id="sRandom" type="checkbox" ${s.randomizeQuestions?'checked':''}> Acak urutan soal</label><label class="check-row"><input id="sActive" type="checkbox" ${s.active!==false?'checked':''}> Ujian aktif</label></div>
  </div>`,footer:`<button class="btn btn-outline" data-cancel>Batal</button><button id="saveSubjectBtn" class="btn btn-primary">Simpan</button>`});
  $('[data-cancel]').onclick=closeModal; $('#saveSubjectBtn').onclick=async()=>{
    const data={name:$('#sName').value.trim(),code:$('#sCode').value.trim().toUpperCase(),durationMinutes:Number($('#sDuration').value||60),token:$('#sToken').value.trim(),scheduleStart:localInputToIso($('#sStart').value),scheduleEnd:localInputToIso($('#sEnd').value),maxWarnings:Number($('#sWarnings').value||3),randomizeQuestions:$('#sRandom').checked,active:$('#sActive').checked,updatedAt:serverTimestamp()};
    if(!data.name||!data.code||!data.token)return toast('Nama, kode, dan token wajib diisi.','warn');
    if(s.id) await updateDoc(doc(db,'subjects',s.id),data); else await addDoc(collection(db,'subjects'),{...data,createdAt:serverTimestamp()}); closeModal();toast('Mata pelajaran disimpan.','success');renderSubjects(currentContainer);
  };
}
async function deleteSubject(id){if(!confirm('Hapus mata pelajaran? Soal subkoleksi tidak otomatis terhapus dari Firestore.'))return;await deleteDoc(doc(db,'subjects',id));toast('Mata pelajaran dihapus.','success');renderSubjects(currentContainer);}

async function renderQuestions(c){
  const subjects=await getAll('subjects');
  c.innerHTML=`<div class="section-head"><div><h3>Bank Soal</h3><p>Buat soal manual atau import dari Excel / Word.</p></div><div class="toolbar"><select id="questionSubject" class="form-control">${subjects.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('')}</select><button id="importBtn" class="btn btn-outline">⇧ Import</button><button id="addQuestionBtn" class="btn btn-primary">+ Soal</button></div></div><div id="questionRoot" class="question-list"></div>`;
  if(!subjects.length){$('#questionRoot').innerHTML=empty('Buat mata pelajaran dahulu','Bank soal membutuhkan mata pelajaran.');return;}
  $('#questionSubject').onchange=()=>loadQuestionList(); $('#addQuestionBtn').onclick=()=>questionForm($('#questionSubject').value); $('#importBtn').onclick=()=>importModal($('#questionSubject').value); await loadQuestionList();
}
async function loadQuestionList(){const sid=$('#questionSubject').value; const snap=await getDocs(query(collection(db,'subjects',sid,'questions'),orderBy('order'))); const qs=snap.docs.map(d=>({id:d.id,...d.data()})); const root=$('#questionRoot');root.innerHTML=qs.length?qs.map((q,i)=>questionCard(q,i)).join(''):empty('Belum ada soal','Tambah soal manual atau gunakan import Excel/Word.');root.querySelectorAll('[data-edit-q]').forEach(b=>b.onclick=()=>questionForm(sid,qs.find(x=>x.id===b.dataset.editQ)));root.querySelectorAll('[data-del-q]').forEach(b=>b.onclick=()=>deleteQuestion(sid,b.dataset.delQ));}
function questionCard(q,i){return `<article class="card question-admin-card"><div class="question-admin-top"><h4>${i+1}. ${escapeHtml(q.question||'')}</h4><div class="toolbar"><button class="btn btn-outline" data-edit-q="${q.id}">Edit</button><button class="btn btn-danger" data-del-q="${q.id}">Hapus</button></div></div><div class="question-admin-options">${(q.options||[]).map((o,j)=>`<div class="${Number(q.correctIndex)===j?'correct':''}">${String.fromCharCode(65+j)}. ${escapeHtml(o)}</div>`).join('')}</div></article>`;}
function questionForm(sid,q={}){const opts=q.options||['','','',''];modal({title:q.id?'Edit Soal':'Tambah Soal',subtitle:'Pilihan ganda 4 opsi.',body:`<label class="field"><span>Pertanyaan</span><textarea id="qText">${escapeHtml(q.question||'')}</textarea></label><div class="form-grid">${[0,1,2,3].map(i=>`<label class="field"><span>Opsi ${String.fromCharCode(65+i)}</span><input id="qOpt${i}" value="${escapeHtml(opts[i]||'')}"></label>`).join('')}<label class="field"><span>Jawaban Benar</span><select id="qCorrect">${[0,1,2,3].map(i=>`<option value="${i}" ${Number(q.correctIndex)===i?'selected':''}>${String.fromCharCode(65+i)}</option>`).join('')}</select></label><label class="field"><span>Poin</span><input id="qPoints" type="number" min="1" value="${Number(q.points||1)}"></label><label class="field span-2"><span>Pembahasan (opsional)</span><textarea id="qExplanation">${escapeHtml(q.explanation||'')}</textarea></label></div>`,footer:`<button class="btn btn-outline" data-cancel>Batal</button><button id="saveQBtn" class="btn btn-primary">Simpan Soal</button>`});$('[data-cancel]').onclick=closeModal;$('#saveQBtn').onclick=async()=>{const data={question:$('#qText').value.trim(),options:[0,1,2,3].map(i=>$(`#qOpt${i}`).value.trim()),correctIndex:Number($('#qCorrect').value),points:Number($('#qPoints').value||1),explanation:$('#qExplanation').value.trim(),updatedAt:serverTimestamp()};if(!data.question||data.options.some(x=>!x))return toast('Pertanyaan dan semua opsi wajib diisi.','warn');if(q.id)await updateDoc(doc(db,'subjects',sid,'questions',q.id),data);else{const snap=await getDocs(collection(db,'subjects',sid,'questions'));await addDoc(collection(db,'subjects',sid,'questions'),{...data,order:snap.size+1,createdAt:serverTimestamp()});}closeModal();toast('Soal disimpan.','success');loadQuestionList();};}
async function deleteQuestion(sid,qid){if(!confirm('Hapus soal ini?'))return;await deleteDoc(doc(db,'subjects',sid,'questions',qid));toast('Soal dihapus.','success');loadQuestionList();}

function importModal(sid){modal({title:'Import Soal',subtitle:'Pilih Excel (.xlsx/.xls) atau Word (.docx).',size:'lg',body:`<div class="callout"><b>Format Excel</b><br>Baris pertama wajib memakai kolom: <code>question, option_a, option_b, option_c, option_d, correct, points, explanation</code>. Kolom <code>correct</code> berisi A/B/C/D.</div><div class="divider"></div><div class="callout"><b>Format Word</b><div class="code-sample">SOAL: 2 + 2 = ...\nA. 2\nB. 3\nC. 4\nD. 5\nJAWABAN: C\nPOIN: 1\nPEMBAHASAN: 2 + 2 = 4\n---\nSOAL: Ibu kota Indonesia adalah ...\nA. Bandung\nB. Jakarta\nC. Surabaya\nD. Medan\nJAWABAN: B</div></div><label class="field"><span>Pilih File</span><input id="questionFile" type="file" accept=".xlsx,.xls,.docx"></label><div id="importPreview" class="hint">Belum ada file dipilih.</div>`,footer:`<button class="btn btn-outline" data-cancel>Batal</button><button id="downloadCsvTemplate" class="btn btn-soft">Unduh Template CSV</button><button id="doImportBtn" class="btn btn-primary">Import Sekarang</button>`});$('[data-cancel]').onclick=closeModal;$('#downloadCsvTemplate').onclick=()=>downloadText('template-soal.csv','question,option_a,option_b,option_c,option_d,correct,points,explanation\n"2 + 2 = ...",2,3,4,5,C,1,"2 + 2 = 4"','text/csv;charset=utf-8');$('#questionFile').onchange=()=>{$('#importPreview').textContent=$('#questionFile').files[0]?`File: ${$('#questionFile').files[0].name}`:'Belum ada file dipilih.'};$('#doImportBtn').onclick=()=>importQuestions(sid);}
async function importQuestions(sid){const file=$('#questionFile').files[0];if(!file)return toast('Pilih file terlebih dahulu.','warn');let rows=[];try{if(/\.xlsx?$|\.xls$/i.test(file.name)){const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array'});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}).map(r=>normalizeImportRow(r));}else if(/\.docx$/i.test(file.name)){const data=await file.arrayBuffer();const result=await mammoth.extractRawText({arrayBuffer:data});rows=parseWordQuestions(result.value);}else return toast('Format file tidak didukung.','error');rows=rows.filter(r=>r.question&&r.options.every(Boolean)&&r.correctIndex>=0);if(!rows.length)return toast('Tidak ada soal valid yang ditemukan. Cek format file.','error');const existing=(await getDocs(collection(db,'subjects',sid,'questions'))).size;for(let start=0;start<rows.length;start+=400){const batch=writeBatch(db);rows.slice(start,start+400).forEach((r,i)=>{const ref=doc(collection(db,'subjects',sid,'questions'));batch.set(ref,{...r,order:existing+start+i+1,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});});await batch.commit();}closeModal();toast(`${rows.length} soal berhasil diimport.`,'success');loadQuestionList();}catch(e){console.error(e);toast(`Import gagal: ${e.message}`,'error',5000);}}
function normalizeImportRow(r){const get=(...keys)=>{for(const k of keys){const found=Object.keys(r).find(x=>x.toLowerCase().trim()===k);if(found)return String(r[found]??'').trim();}return''};const correct=get('correct','jawaban','kunci').toUpperCase();return{question:get('question','soal','pertanyaan'),options:[get('option_a','a','opsi_a'),get('option_b','b','opsi_b'),get('option_c','c','opsi_c'),get('option_d','d','opsi_d')],correctIndex:'ABCD'.indexOf(correct[0]),points:Number(get('points','poin')||1),explanation:get('explanation','pembahasan')};}
function parseWordQuestions(text){return text.split(/\n\s*---+\s*\n/g).map(block=>{const lines=block.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const find=prefix=>{const l=lines.find(x=>x.toUpperCase().startsWith(prefix));return l?l.slice(prefix.length).trim():''};const correct=find('JAWABAN:').toUpperCase();return{question:find('SOAL:'),options:['A.','B.','C.','D.'].map(p=>find(p)),correctIndex:'ABCD'.indexOf(correct[0]),points:Number(find('POIN:')||1),explanation:find('PEMBAHASAN:')};});}

async function renderStudents(c){
  c.innerHTML=`<div class="section-head"><div><h3>Akun Siswa</h3><p>Buat username dan password untuk siswa.</p></div><button id="addStudentBtn" class="btn btn-primary">+ Buat Akun</button></div><div id="studentTableRoot"></div>`;$('#addStudentBtn').onclick=studentForm;const users=(await getAll('users')).filter(x=>x.role==='student').sort((a,b)=>(a.displayName||'').localeCompare(b.displayName||''));$('#studentTableRoot').innerHTML=users.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Nama</th><th>Username</th><th>Status</th><th>Dibuat</th></tr></thead><tbody>${users.map(u=>`<tr><td><b>${escapeHtml(u.displayName||'-')}</b></td><td>${escapeHtml(u.username||'-')}</td><td><span class="badge ${u.active!==false?'badge-green':'badge-slate'}">${u.active!==false?'Aktif':'Nonaktif'}</span></td><td>${formatDateTime(u.createdAt)}</td></tr>`).join('')}</tbody></table></div>`:empty('Belum ada akun siswa','Klik Buat Akun untuk menambahkan siswa.');
}
function studentForm(){modal({title:'Buat Akun Siswa',subtitle:'Username akan dipakai siswa saat login.',body:`<label class="field"><span>Nama Siswa</span><input id="stuName" placeholder="Nama lengkap"></label><label class="field"><span>Username</span><input id="stuUsername" placeholder="siswa001"></label><label class="field"><span>Password</span><input id="stuPassword" type="text" placeholder="Minimal 6 karakter"></label><div class="callout warn">Simpan/catat password setelah akun dibuat. Pada versi GitHub Pages murni, admin tidak dapat mengganti password akun Firebase milik pengguna lain tanpa backend Admin SDK.</div>`,footer:`<button class="btn btn-outline" data-cancel>Batal</button><button id="createStudentBtn" class="btn btn-primary">Buat Akun</button>`});$('[data-cancel]').onclick=closeModal;$('#createStudentBtn').onclick=createStudent;}
async function createStudent(){const displayName=$('#stuName').value.trim(),username=normalizeUsername($('#stuUsername').value),password=$('#stuPassword').value;if(!displayName||!username||password.length<6)return toast('Nama, username dan password minimal 6 karakter wajib diisi.','warn');try{const secondary=getApps().find(a=>a.name==='StudentCreator')||initializeApp(firebaseConfig,'StudentCreator');const secondaryAuth=getAuth(secondary);const cred=await createUserWithEmailAndPassword(secondaryAuth,usernameToEmail(username),password);await setDoc(doc(db,'users',cred.user.uid),{username,displayName,role:'student',active:true,createdAt:serverTimestamp(),createdBy:'admin'});closeModal();toast('Akun siswa berhasil dibuat.','success');renderStudents(currentContainer);}catch(e){console.error(e);toast(e.code==='auth/email-already-in-use'?'Username sudah dipakai.':`Gagal membuat akun: ${e.message}`,'error',5000);}}

async function renderScores(c){
  c.innerHTML=`<div class="section-head"><div><h3>Nilai Ujian</h3><p>Semua hasil ujian yang sudah dikumpulkan.</p></div><div class="toolbar"><input id="scoreSearch" class="search" placeholder="Cari siswa / mapel"><button id="exportScoresBtn" class="btn btn-outline">↓ Export CSV</button></div></div><div id="scoreTableRoot"></div>`;
  const attempts=(await getAll('attempts')).filter(x=>x.status==='submitted').sort((a,b)=>dateMs(b.submittedAt)-dateMs(a.submittedAt)); const draw=()=>{const k=$('#scoreSearch').value.trim().toLowerCase();const filtered=attempts.filter(x=>`${x.studentName} ${x.username} ${x.subjectName}`.toLowerCase().includes(k));$('#scoreTableRoot').innerHTML=filtered.length?scoreTable(filtered):empty('Nilai tidak ditemukan','Belum ada data yang sesuai.')};draw();$('#scoreSearch').oninput=draw;$('#exportScoresBtn').onclick=()=>exportScores(attempts);
}
function scoreTable(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Siswa</th><th>Mapel</th><th>Sesi</th><th>Nilai</th><th>Benar</th><th>Pelanggaran</th><th>Selesai</th></tr></thead><tbody>${rows.map(a=>`<tr><td><b>${escapeHtml(a.studentName||'-')}</b><br><small>${escapeHtml(a.username||'')}</small></td><td>${escapeHtml(a.subjectName||'-')}</td><td>${escapeHtml(a.session||'-')}</td><td><span class="badge ${Number(a.score)>=75?'badge-green':'badge-red'}">${Number(a.score||0)}</span></td><td>${a.correctCount||0}/${a.totalQuestions||0}</td><td>${a.violations||0}</td><td>${formatDateTime(a.submittedAt)}</td></tr>`).join('')}</tbody></table></div>`;}
function exportScores(rows){const header=['Nama','Username','Mata Pelajaran','Sesi','Nilai','Benar','Total Soal','Pelanggaran','Waktu Selesai'];const lines=[header.join(','),...rows.map(a=>[a.studentName,a.username,a.subjectName,a.session,a.score,a.correctCount,a.totalQuestions,a.violations,formatDateTime(a.submittedAt)].map(csvEscape).join(','))];downloadText(`nilai-ujian-${new Date().toISOString().slice(0,10)}.csv`,lines.join('\n'),'text/csv;charset=utf-8');}

async function renderSettings(c){const snap=await getDoc(doc(db,'settings','app'));const s=snap.exists()?snap.data():{};c.innerHTML=`<div class="section-head"><div><h3>Pengaturan Aplikasi</h3><p>Identitas dasar yang tampil di aplikasi.</p></div></div><div class="card card-pad" style="max-width:760px"><div class="form-grid"><label class="field span-2"><span>Nama Sekolah</span><input id="setSchool" value="${escapeHtml(s.schoolName||'CBT Sekolah')}"></label><label class="field span-2"><span>Judul Ujian</span><input id="setTitle" value="${escapeHtml(s.examTitle||'Ujian Online')}"></label><label class="field span-2"><span>Nilai KKM</span><input id="setKkm" type="number" min="0" max="100" value="${Number(s.kkm||75)}"></label></div><div class="action-row"><button id="saveSettingsBtn" class="btn btn-primary">Simpan Pengaturan</button></div></div>`;$('#saveSettingsBtn').onclick=async()=>{await setDoc(doc(db,'settings','app'),{schoolName:$('#setSchool').value.trim()||'CBT Sekolah',examTitle:$('#setTitle').value.trim()||'Ujian Online',kkm:Number($('#setKkm').value||75),updatedAt:serverTimestamp()},{merge:true});toast('Pengaturan disimpan.','success');};}

function dateMs(v){if(!v)return 0;return v.toDate?v.toDate().getTime():new Date(v).getTime()||0;}
function empty(title,text){return `<div class="card empty-state"><div class="empty-icon">□</div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(text)}</p></div>`;}
